### ISSUE TITLE
Is it convenient to provide preprocessing code? 

### ISSUE THREAD

**Issue by RandomTuringDuck** [pranav-ust/BERT-keyphrase-extraction#3]
Is it convenient to provide preprocessing code? Just mark the location of the complete keyphrase?

**Comment by pranav-ust** [comment]
I have kinda lost the preprocessing code, but my friend's repo has some hints on how we did it. https://github.com/ibatra/BERT-Keyword-Extractor/blob/master/BERT-Keyword%20Extractor.ipynb
